### ISSUE TITLE
unsupported hive

### ISSUE THREAD

**Issue by Displayray** [ironSource/node-regedit#102]
My code: 
await regedit.createKey(["HKEY_LOCAL_MACHINE\\SOFTWARE\\PFM"]);
        regedit.putValue({
          "HKEY_LOCAL_MACHINE\\SOFTWARE\\PFM": {
            myname: {
              value: myvalue,
              type: "REG_SZ",
            },
          },
        });

**Comment by lecepin** [comment]
+1

**Comment by MLDMoritz** [comment]
Version 5.00 seems to work for me

**Comment by kessler** [comment]
this is fixed now, sorry for the delayed response to this. published on 5.1.2
