### ISSUE TITLE
Command failed

### ISSUE THREAD

**Issue by ZeeLyn** [ironSource/node-regedit#107]
![image](https://user-images.githubusercontent.com/17895675/174939700-f60995c2-519d-476f-b5c0-8cf8eedbade5.png)
I confirm that the path of the.wsf file is correct, but I still throw an error

**Comment by ZeeLyn** [comment]
Stop execution by Microsoft Defender
![image](https://user-images.githubusercontent.com/17895675/174952196-dc9e2c37-a1f7-4efd-b0fa-d8cdc1db82a6.png)

**Comment by kessler** [comment]
not sure exactly what I see here... but I'll venture a guess, this might be a false positive by ms defender?
