### ISSUE TITLE
Undefined childProcess.execFile

### ISSUE THREAD

**Issue by marco987** [ironSource/node-regedit#112]
Hello. Trying to execute:

```
const regedit = require('regedit').promisified
var listResult = regedit.list('HKCU\\SOFTWARE')
console.log(listResult)
```
I get the following error:

```
Uncaught TypeError: Cannot read properties of undefined (reading 'apply') at execFile
var child = childProcess.execFile.apply(childProcess, arguments)
```
Can I get some suggestions please?

**Comment by kessler** [comment]
Hi @marco987 sorry for the extremely late response and for not responding to your email as well.
I'm a not getting the same error as you, only the (expected) output `Promise { <pending> }`. the promisified version should be used with `async/await` or `Promise` apis.
