### ISSUE TITLE
How do I use ES6 syntax?

### ISSUE THREAD

**Issue by ll21121** [ironSource/node-regedit#114]
`import { list } from "regedit";
list([path], function(error:any, result:any){
		...
	})
`

error msg:  
TypeError: $u.inherits is not a function
    at node_modules/stream-slicer/index.js (index.js:4:4)
    at __require (chunk-JEXKZRFY.js?v=6827b305:12:50)
    at node_modules/regedit/index.js (index.js:7:22)
    at __require (chunk-JEXKZRFY.js?v=6827b305:12:50)
    at index.js:573:1
(匿名) @ index.ts:107

 I'm a back-end developer. I don't know much about this

**Comment by kessler** [comment]
are you using typescript ?

**Comment by ll21121** [comment]
I used cool-admin template,  https://show.cool-admin.com/。  vue +ts + vite
![image](https://user-images.githubusercontent.com/26063196/219988521-4040e73b-0657-4346-a6fc-a119aab4882b.png)

**Comment by kessler** [comment]
stream slicer is a very old lib I wrote a long time ago (and ditched it a long time ago for better modules like `split`), anyways:
<img width="422" alt="image" src="https://user-images.githubusercontent.com/147367/220217446-b5bba213-8222-4f3b-b2cb-b01ba47fe070.png">

line 4 here just uses the built in nodejs `util.inherits` and while it's legacy, it's not deprecated... so honestly, this shouldn't happen. 

Could you try running your code using `node` in command line (and nothing else no typescript or other things) see if it works?

**Comment by ll21121** [comment]
![image](https://user-images.githubusercontent.com/26063196/220228086-02c08d33-f5d1-4ae5-afdb-bfdc082d4a13.png)
look, everything is ok。  but  how to  use "import" , can you write a simple example?

**Comment by kessler** [comment]
this should work:

```js
import { promisified as regedit } from 'regedit'

async function main() {
  await regedit.list()
}

main()
```
