### ISSUE TITLE
Test fails because the string is not in the correct case

### ISSUE THREAD

**Issue by arieljannai** [ironSource/node-regedit#15]
At least on my computer, [this test](https://github.com/ironSource/node-regedit/blob/master/test/regedit.test.js#L98) failed because the key in my registry is in uppercase - `SOFTWARE` and not `Software`

I think it will be fine to make the check case insensitive, cause either way windows doesn't care the case of the registry key - it could also be `SoFTwarE`.

**Comment by kessler** [comment]
Thanks. Will update this soon

**Comment by nhz-io** [comment]
Duplicate of #36
