### ISSUE TITLE
Error niceties

### ISSUE THREAD

**Issue by vweevers** [ironSource/node-regedit#16]
Hiya Kessler.

FIY, I took the error codes you had here and made [wmi-errors](https://github.com/vweevers/wmi-errors). You might consider using it for `node-regedit` too, because you get a call-stack captured at the time you create the error, a simple hierarchy for `instanceof` checks, and some useful properties.

**Comment by eneurons** [comment]
Sounds great lets do it :-)

**Comment by kessler** [comment]
Vincent, I have you permissions on the repo, can you integrate the new module?

**Comment by kessler** [comment]
bump :)

**Comment by vweevers** [comment]
First I must say: I made this for `win-detect-browsers`, which I was working on back then, but haven't finished that work, so `wmi-errors` hasn't seen any real usage yet. And atm I can't remember if I was happy with its API yet

**Comment by kessler** [comment]
Alrighty, shall I close the issue in the meanwhile?

**Comment by vweevers** [comment]
Sure. I'll let you know
