### ISSUE TITLE
Streaming Function is redundant, when there is no registry key found.

### ISSUE THREAD

**Issue by vincent1173** [ironSource/node-regedit#17]
Hi,
I'm trying to find whether the registry key exists using regedit. 

```
 regedit.list(/*reg key here */)
    .on('data',function(data) {
      console.log("data found");
    })
    .on('error',function(error){console.log("error!")})
    .on('finish',function() {console.log("Finish");});

```

But, the control doesn't fall to finish , when no suck key is found. Instead, it prints 'error' twice.

**Comment by kessler** [comment]
@vincentdass is the problem resolved?

**Comment by kessler** [comment]
@vincentdass could you send a PR or share the code here?

**Comment by kessler** [comment]
tested, not an issue anymore (don't know why though... :-( )
