### ISSUE TITLE
Blocking xplat node solution due to regedit package

### ISSUE THREAD

**Issue by Ajay-MS** [ironSource/node-regedit#19]
Hello team, 

We build an xplat solution in which we are using regedit as package. At runtime we are using regedit only for windows platform but it is since during build time on linux platform, regedit pacakge is throwing error as **Not compatible with your operating system or architecture: regedit@2.2.6**
Because in node-regedit [package.json](https://github.com/ironSource/node-regedit/blob/master/package.json)
  "os": [
    "win32"
  ],
This is stopping us using regedit on a cross plat solution.

**Comment by kessler** [comment]
@Ajay-MS is this still relevant? if so let me know.
