### ISSUE TITLE
How to delete value?

### ISSUE THREAD

**Issue by WinterWoods** [ironSource/node-regedit#20]
How to delete value?thx

**Comment by longang520** [comment]
@kessler

**Comment by kessler** [comment]
To delete the whole key:
https://github.com/ironSource/node-regedit#regeditdeletekeystringarray-function

To "clear" a value use putValue with zero length string or something else that is the equivalent of null / zero for that particular key type

**Comment by kessler** [comment]
@longang520 is this issue resolved?
