### ISSUE TITLE
Error with large numbers in REG_DWORD and REG_QWORD

### ISSUE THREAD

**Issue by zariweyo** [ironSource/node-regedit#21]
To solve this, please, in file regUtil.vbs replace CInt to CLng. (lines 37 and 43).

Thanks

**Comment by kessler** [comment]
@zariweyo could you please provide some code that will help me recreate the problem? thanks

**Comment by juanjo75es** [comment]
I updated the code like zariweyo said but still doesn't work if I use createKey and a number is large.

**Comment by juanjo75es** [comment]
Code that fails (the problem is in the Attributes value):

                                                  regedit.createKey([s3], function(err) {

                                                          let valuesToPut = {};
                                                          valuesToPut[s3] = {
                                                            'FolderValueFlags': {
                                                              value: 0x28,
                                                              type: 'REG_DWORD'
                                                            },
                                                            'Attributes': {
                                                              value: 0xF080004D,  
                                                              type: 'REG_DWORD'
                                                            }
                                                          };

**Comment by kessler** [comment]
@juanjo75es currently very busy... so it will take time to get to this. However, if you run into a solution in the meanwhile, please don't hesitate to send a PR

**Comment by nhz-io** [comment]
`CLng` overflows at `0x80000000`. Need to use `CDb` for writing and `Long to ULong` correction workaround

**Comment by nhz-io** [comment]
## REG_QWORD
* No conversion needed - `SetQWORDValue` accepts a `String`
* **writing** is limited to values below `9007199254740993` [Precision](http://www.rlmueller.net/Precision.htm)
* **reading** is unaffected by precision limit

**I dont see a way to overcome the precision limit on writing** :cry:

**Comment by nhz-io** [comment]
Fixed by #25

**Comment by juanjo75es** [comment]
@kessler Well ... I solved my problem using:

```
var exec = require('child_process').exec;
exec( "reg add (...)" , function(error, stdout, stderr){});

```
But I guess it won't help you.

**Comment by kessler** [comment]
@juanjo75es thanks for sharing the solution :)
