### ISSUE TITLE
Cannot open regedit folder name with special character

### ISSUE THREAD

**Issue by orancezii** [ironSource/node-regedit#22]
I try

    regedit.list([
    "HKLM\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\nbi-nb-base-8.0.2.0.201411181905"]).on('data', function (entry) {
    console.log(entry);   
})

It's not work. It cannot open that path,

I think because folder name "nbi-nb-base-8.0.2.0.201411181905" has special character.

I try to add bracket , quote,

**example** : {folder_name} or "folder_name" or "{folder_name}".

It's also not working. Can anyone give me a suggestion please?

**Comment by orancezii** [comment]
Please help

**Comment by kessler** [comment]
@orancezii sorry for the delayed response. Currently very busy. Will make for this in the close weekend

**Comment by nhz-io** [comment]
## Cannot reproduce

There is nothing special about `nbi-nb-base-8.0.2.0.201411181905`
The test passes. See commit: 79cc6e5
