### ISSUE TITLE
Cannot find module 'regedit'

### ISSUE THREAD

**Issue by Chinalijian** [ironSource/node-regedit#24]
Hi,
I'm trying to get registry information
`    var regedit = require('regedit')
    regedit.list('HKCU\\SOFTWARE\\BI\\EcgLab', function(err, result) {
        console.log('result:' + JSON.stringify(result['HKCU\\SOFTWARE\\BI\\EcgLab']))
        if (err != null) {
            console.log('exec error:' + err)
        }
    })`

but , run the installation package, The pop-up error message: 
![error](https://cloud.githubusercontent.com/assets/28856001/26478690/81cedefa-4200-11e7-8868-e10ee4756eb0.png)

Thanks!

**Comment by nhz-io** [comment]
Please provide more info about your environment. What is this screenshot?

**Comment by kessler** [comment]
@Chinalijian can you attach your NPM install output?

**Comment by CherryDT** [comment]
@nhz-io This appears to be an exception message from Electron

**Comment by nhz-io** [comment]
@CherryDT AHA! Thanks for deduction. I will have to setup mock electron project to test it. Though I suspect someone forgot to `npm i`

**Comment by kessler** [comment]
@CherryDT you should take a look at this: #13 
In the meanwhile I'm closing this issue, it's not a problem or a bug in `regedit`

**Comment by CherryDT** [comment]
I just pointed out that the screenshot may come from Electron, I don't use it there ;)
@Chinalijian you should take a look at this: #13

**Comment by kessler** [comment]
@CherryDT sorry ;-)
