### ISSUE TITLE
"describe is not defined"

### ISSUE THREAD

**Issue by odeer95** [ironSource/node-regedit#26]
Hi to all,
I'm trying to launch **regedit.test.js**, but I think there's something that I'm doing in a wrong way...

P.s. Please don't be bad, I'm new to node.js :(

![image](https://cloud.githubusercontent.com/assets/29045734/26558342/2f9ebd4e-44a8-11e7-909f-1e1ecbc28be1.png)

**Comment by nhz-io** [comment]
@odeer95 Just do:
```
npm test
```

**Comment by odeer95** [comment]
![image](https://cloud.githubusercontent.com/assets/29045734/26559682/6d4e7414-44b1-11e7-8b4f-ea869edc65ca.png)

**Comment by nhz-io** [comment]
@odeer95:
```
npm i
npm test
```
**RTFM** https://docs.npmjs.com/
