### ISSUE TITLE
Writing REG_DWORD values with more than 16 bits is broken

### ISSUE THREAD

**Issue by CherryDT** [ironSource/node-regedit#39]
Trying to set a `REG_DWORD` with a value of e.g. `1000000` causes an error `vbscript process reported unknown error code 1`.

This is caused by a runtime error in VBScript due to an overflow when calling `CInt` (note that VBScript's `Integer` is a signed 16-bit type). I guess what you actually wanted is `CLng` (VBScript's `Long` is a signed 32-bit type).

**Comment by nhz-io** [comment]
@CherryDT Could you try cloning repo and running tests? 
You can also try installing the package directly from github:
```
npm i git+https://github.com/ironSource/node-regedit
```
This issue looks related to #21 which will be fixed when we publish `v2.2.7`

**Comment by CherryDT** [comment]
You are right, it's a duplicate, I didn't look at closed issues.

**Comment by kessler** [comment]
@CherryDT  published 2.2.7
