### ISSUE TITLE
making createKey/delete easier ?

### ISSUE THREAD

**Issue by rafipiccolo** [ironSource/node-regedit#4]
the syntax is a bit repetitive when you want to create a key and add something in it (especially a default value). cound you modify the createKey function to allow a value parameter ?

```
function regedit_createKey(key, value, callback) {
    regedit.createKey(key, function(err) {
            var obj = {};
            obj[key] = {
                '@': {
                   value: value,
                   type: 'REG_DEFAULT'
                }
            }
            regedit.putValue(obj, callback))
    });
}
```

Also, when you want to remove a key it fails with acces denied if there are other keys inside.
would it be possible to just remove thoses keys recursively. I don't know how to do it, but maybe with list method ?

**Comment by kessler** [comment]
Excellent suggestions. I will try to implement those in a few days.
