### ISSUE TITLE
Cannot package into electron app. 

### ISSUE THREAD

**Issue by maisnamraju** [ironSource/node-regedit#41]
I tried using the package on an electron application and thought it works find on development, it doesn't work in the bundled version. Posting a screenshot 

![screen shot 2017-08-02 at 4 13 01 pm](https://user-images.githubusercontent.com/2786378/28870535-428c06cc-779e-11e7-8b0a-7cc64ffe9c5b.png)

**Comment by kiuKisas** [comment]
which packager do you use ? Work fine with `electron-builder`

**Comment by muminasaad** [comment]
Dear the problem is that the path to the wsf file is inside the app.asar file,
You have to options, either you disable asar packaging, or you edit the baseCommand function to change to an external path that will contain the vbs folder

**Comment by kessler** [comment]
fixed at  e41c9a88af6c5addb5bf08995f74482774084ae5
