### ISSUE TITLE
Critical error?

### ISSUE THREAD

**Issue by Pomax** [ironSource/node-regedit#42]
I'm hitting a ton of things like
```
{"HKLM\\Software\\Wow6432Node\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\{F79F4961-D0D8-2893-B81D-7A60F300ED6F}":
J:\Junctions\Users\Mike\Documents\Git\temp\pluginboutique\node_modules\regedit\vbs\regList.wsf(0, 2) SWbemObjectEx: Critical error
```
without a way to apparently either suppress those errors, or actually do anything about them (because the error in no way explains what went wrong, and what I need to change as a dev to not run into this)

**Comment by kessler** [comment]
@Pomax is it possible for you to submit some piece of code so I can recreate this?

**Comment by Pomax** [comment]
I no longer have any reproducing code per se, but https://github.com/ironSource/node-regedit/issues/43 was a rewrite of the code to prevent running into these errors. Rewriting that to synchronous rather than callback code should show millions of these errors again.
