### ISSUE TITLE
Using Electron - Not working when packed in ASAR

### ISSUE THREAD

**Issue by HekMe** [ironSource/node-regedit#50]
Ahoy,

I'm using this from within electron which is working while not in asar.
When i pack it in asar it returns error "Input Error: Can not find script file 'path-to-folder\resources\app.asar\node_modules\regedit\vbs\regList.wsf'".
Also when pack everything else, except this, it returns the same error.
It looks like that while it's unpacked it still looks for files in the asar archive.

Thanks

**Comment by Halo4356** [comment]
I am going to fork the repository and add in a fix for this exact situation.

The culprit is at line 340 of `index.js`:

```
    return ['//Nologo', path.join(__dirname, 'vbs', cmd), arch]
```

This error is fixed using:

```
    return ['//Nologo', path.join(__dirname, 'vbs', cmd).replace('app.asar', 'app.asar.unpacked'), arch]
```

I'm not sure if it is safe to merge into upstream but I'd be willing to submit a pull request if deemed necessary.

**Comment by hektor157** [comment]
Thanks for answer.
Is it working at the moment? :)
I haven't noticed your reply, sorry.

**Comment by Halo4356** [comment]
With my change, yeah node-regedit works fine, unpacked from the ASAR.

here is the commit:

https://github.com/Halo4356/node-regedit/commit/252bf1bceb891249949e264108f94c68a356713a

**Comment by kessler** [comment]
@muminasaas PR should solve this:  e41c9a88af6c5addb5bf08995f74482774084ae5
