### ISSUE TITLE
RegList outputing key to console.

### ISSUE THREAD

**Issue by als9xd** [ironSource/node-regedit#53]
I ended up removing the "Write" lines within `vbs/regList.wf` and that appears to have fixed it. Is this by design?

Here is the code I'm using:

```javascript
const regedit = require('regedit');
regedit.list("HKCU\\SOFTWARE",function(err,results){
	if(err){
		console.log(err);
		return;
	}
	console.log('done');
});
```

**Comment by kessler** [comment]
@als9xd running this code on a brand new windows 10 machine did not produce any kind of unexpected output:

![image](https://user-images.githubusercontent.com/147367/41203798-bce0ad60-6ce4-11e8-94ec-120e5a8b483b.png)

The vbscript and node communicate via stdout, this is why the vbscript writes the result to it.
