### ISSUE TITLE
Promise support?

### ISSUE THREAD

**Issue by FireController1847** [ironSource/node-regedit#55]
Is it possible to get support for promises instead of using callbacks to prevent [callback hell](http://callbackhell.com/)?

[Rage Edit](https://www.npmjs.com/package/rage-edit) already has this implementation, so it may be time to catch up.

**Comment by kessler** [comment]
@FireController1847 I strongly suggest that next time you ask someone to do something for you with their free time, you should tone down on the condescending statements.

As for your statement regarding, callback hell, I suggest this read: http://thecodebarbarian.com/2015/03/20/callback-hell-is-a-myth

**Comment by nhz-io** [comment]
@FireController1847 https://nodejs.org/docs/latest-v8.x/api/util.html#util_util_promisify_original

**Comment by FireController1847** [comment]
Condescending statements?

**Comment by nhz-io** [comment]
@FireController1847 ` , so it may be time to catch up.` &larr; this
