### ISSUE TITLE
deleteValue

### ISSUE THREAD

**Issue by JasminDreasond** [ironSource/node-regedit#61]
I'm trying to create the function to delete a value from a key. But exist a problem :c 
`vbscript process reported unknown error code 1`

This script inside the regUtil.vbs not working.  (I created the function)

```
Function RemoveValue(constHive, strSubKey, strValueName)		

	RemoveValue = DeleteValue(constHive, strSubKey, strValueName)

End Function
```

The variables  "constHive", "strSubKey", "strValueName" is working. The problem is the DeleteValue() only.

The commit: 
https://github.com/JasminDreasond/node-regedit/commit/2075afed6fba48f053f291487ed81bb8e7a23c9c
https://github.com/JasminDreasond/node-regedit/commit/4e3a8e93424a63dc4d4fec7aa34c4b14e972c1a1

**Comment by Connum** [comment]
Any progress on this? I need to delete a value as well, but this functionality is still listed as "TODO".

**Comment by LOHT03** [comment]
I don't think that the `DeleteValue` function has been created. Is there a status update on when this feature will be introduced?

**Comment by xiaoyaoseng** [comment]
I also try to fix this function but failed. Then I use node-exec to solve it..
The example is: 
`var shell = require('node-exec');
function deleteValue(key, value) {
	query = 'REG DELETE "' + key + '" /v ' + value + ' /f';
	shell.run(query).then(function(res) {
		console.log('delete success');
	});
}
deleteValue(regKey, regValue);
`

**Comment by xiaoyaoseng** [comment]
@JasminDreasond I hope it will help some one.
