### ISSUE TITLE
module not working when electron app launched at windows startup

### ISSUE THREAD

**Issue by nikhell86** [ironSource/node-regedit#74]
We are using npm-regedit module to read/write registry in Windows. We are using it in an electron app. Normally when we run the application it works fine but when we set the app to run automatically at startup the regedit module fails when app starts at startup. We get the following error on reading "HKCU/SOFTWARE":
Error: Command failed: cscript.exe //Nologo D:\CodeLathe\Workspace\cl-fc-client\clouddrive2service\ui\dist_electron\win-unpacked\resources\app.asar\vbs\regList.wsf A HKCU\SOFTWARE

Opening the app manually after startup works fine

**Comment by tytech3** [comment]
Strange, my app did this as well, but it didn't stop when opening it manually. Did you perhaps miss this?:

https://www.npmjs.com/package/regedit#a-note-about-electron

**Comment by zhangkaixuan** [comment]
ah...  my app did this as well....  how to fix it?

**Comment by kessler** [comment]
did the note about electron helped?

**Comment by nikhell86** [comment]
no the note in electron did not help .. We stopped using this module due to this issue

**Comment by kessler** [comment]
I see.
Do you want us to debug this together or are you happy with your other solution? (in which case I will proceed to close this issue)

**Comment by nikhell86** [comment]
I am happy with my solution. If you want to debug it, it's easy to recreate, we just need a minimal electron app which runs at Windows startup. We need to try doing operations with this module in app.on('ready') event.. If you need any help I could try to find some time out to help

**Comment by kessler** [comment]
@nikhell86 if you want to create a repo with a minimal app and a script that installs it on a windows machine to launch at startup it will be a tremendous help

**Comment by HwangTaehyun** [comment]
Same problem in window service. I changed my code that always use externalVBSLocation and always use setExternalVBSLocation function in dev and prod electron app

**Comment by kessler** [comment]
@HwangTaehyun we will need a minimal recreation of the problem in order to help.

**Comment by A-ANing** [comment]
https://github.com/ironSource/node-regedit/issues/60#issuecomment-1635270787

this

**Comment by A-ANing** [comment]
> We are using npm-regedit module to read/write registry in Windows. We are using it in an electron app. Normally when we run the application it works fine but when we set the app to run automatically at startup the regedit module fails when app starts at startup. We get the following error on reading "HKCU/SOFTWARE": Error: Command failed: cscript.exe //Nologo D:\CodeLathe\Workspace\cl-fc-client\clouddrive2service\ui\dist_electron\win-unpacked\resources\app.asar\vbs\regList.wsf A HKCU\SOFTWARE
> 
> Opening the app manually after startup works fine

Hi, I used Electron, just like your situation. Which plugin did you switch to and access the registry

**Comment by nikhell86** [comment]
> > We are using npm-regedit module to read/write registry in Windows. We are using it in an electron app. Normally when we run the application it works fine but when we set the app to run automatically at startup the regedit module fails when app starts at startup. We get the following error on reading "HKCU/SOFTWARE": Error: Command failed: cscript.exe //Nologo D:\CodeLathe\Workspace\cl-fc-client\clouddrive2service\ui\dist_electron\win-unpacked\resources\app.asar\vbs\regList.wsf A HKCU\SOFTWARE
> > Opening the app manually after startup works fine
> 
> Hi, I used Electron, just like your situation. Which plugin did you switch to and access the registry

I created a c++ utility to access registry
