### ISSUE TITLE
Expand upon 'a note about electron'

### ISSUE THREAD

**Issue by technicallyty** [ironSource/node-regedit#75]
Currently trying to package my electron + react application. I'm unable to push through the regedit stuff as far as moving the .wsf files out of the asar packager. The docs don't really make it clear as to what we are supposed to be doing. Would it be possible to get a more concise write up on this process? Perhaps a working tutorial file?

I got it to work with :
https://github.com/ironSource/node-regedit/issues/60#issuecomment-510346232

Can the readme be updated to include this information?

**Comment by methodbox** [comment]
Seems like a good opportunity for a PR ;) - but the README is how I got here, actually, from #60, since your comment links to that issue.
