### ISSUE TITLE
regedit.list yields keys only

### ISSUE THREAD

**Issue by Johannes0Horn** [ironSource/node-regedit#76]
Hey,
i was trying to get some registry eintries using:
```
regedit.list(['HKCU\\SOFTWARE', 'HKLM\\SOFTWARE'], function(err, result) {
		console.log(result);
		var HKCU = result["HKCU\\SOFTWARE"];
		var HKLM = result["HKLM\\SOFTWARE"];
		console.log("values:", HKCU["values"]);
		console.log("values:", HKLM["values"]);
}
```
![image](https://user-images.githubusercontent.com/22841259/79217387-18b12480-7e4f-11ea-92c0-49924ad3cce5.png)

According to the console output, it seems like regedit.list only yields the keys but not the values. 
Config:
Windows 10 64Bit
Node.js v12.16.2, also tried Node 8
regedit 3.0.3

I am grateful for every idea :)

**Comment by dtboy1995** [comment]
same issue

**Comment by omiinaya** [comment]
same here

**Comment by M1cr0M1nd** [comment]
@Johannes0Horn @dtboy1995 @omiinaya 
Are you sure you have values under 'HKCU\\SOFTWARE' & 'HKLM\\SOFTWARE'?
I have no values there and when manually adding one an running the script above everything works.

If you're talking about values not coming back as an empty object it will as of version 5.0.0

**Comment by kessler** [comment]
@Johannes0Horn  closing this issue, please reopen if needed
