### ISSUE TITLE
Compressing node app to an exe

### ISSUE THREAD

**Issue by han0idx** [ironSource/node-regedit#78]
Im trying to compress my app.js to a standalone exe , i use this simple command:
`pkg app.js`

But i keep having this error:
`Error: vbscript process reported unknown error code 1`

i tried other solution but nothing works :( anyone know how to solve this ?

**Comment by tymmesyde** [comment]
Same for me
Even if I run my compiled script with the `electron .` command I get this error.
It works fine on a development environment.

**Comment by kessler** [comment]
@han0idx since regedit uses additional non-javascript script files, its possible the packager does not think to include them.
@tymmesyde did you read the [node about electron](https://github.com/ironSource/node-regedit#a-note-about-electron)?

**Comment by kessler** [comment]
I'm closing this, please reopen if needed

**Comment by iSued** [comment]
#70 I've answered here if someone needs

**Comment by juxnpxblo** [comment]
https://github.com/kessler/node-regedit/issues/70 just posted a solution for electron-forge
