### ISSUE TITLE
putValue with empty string for value fails silently

### ISSUE THREAD

**Issue by CharlieHess** [ironSource/node-regedit#8]
An empty string is a valid value for [lots of things](https://msdn.microsoft.com/en-us/library/aa767914(v=vs.85).aspx), but when I attempt to set it using `putValue`, it fails silently.
``` javascript
let values = {
  'HKCR\\Foo': {
    'URL Protocol': {
      value: "",
      type: 'REG_SZ'
    }
  }
};
regedit.putValue(values, (err) => {
  // Never gets here
}
```

**Comment by kessler** [comment]
@CharlieHess 2.2.5 should fix this problem. Do let me know if it doesn't.
