### ISSUE TITLE
regedit.list yields keys only

### ISSUE THREAD

**Issue by dtboy1995** [ironSource/node-regedit#81]

**Comment by nuryagdym** [comment]
+1

**Comment by kessler** [comment]
@M1cr0M1nd can you try this please?

**Comment by M1cr0M1nd** [comment]
@dtboy1995 @nuryagdym 
Are you sure you have values under 'HKCU\SOFTWARE' & 'HKLM\SOFTWARE'?
I have no values there and when manually adding one and running list everything works.

If you're talking about values not coming back as an empty object it will as of version 5.0.0

**Comment by kessler** [comment]
I'm closing this and we'll keep track of this on #76
