### ISSUE TITLE
Lists few values for the Internet Setting registry path

### ISSUE THREAD

**Issue by hassanahmad32** [ironSource/node-regedit#85]
Hi,

I am trying to get the windows proxy setting from the below registry path by using list method:
HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Internet Settings

list method returns only few values as below logs:
{"HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Internet Settings":{"keys":["5.0","Connections","Lockdown_Zones","ZoneMap","Zones"],"values":{"User Agent":{"type":"REG_SZ","value":"Mozilla/4.0 (compatible; MSIE 8.0; Win32)"},"IE5_UA_Backup_Flag":{"type":"REG_SZ","value":"5.0"},"ZonesSecurityUpgrade":{"type":"REG_BINARY","value":[59,0,202,95,61,214,210,1]},"EnableNegotiate":{"type":"REG_DWORD","value":1}}}}

I can see there are almost 28 values. But list only returns 4 values.

Could anyone help me to resolve this issue.

**Comment by kessler** [comment]
@hassanahmad32 
Sorry we're not so active here lately. Could you please attach a code example or update if this issue was resolved or not.

**Comment by M1cr0M1nd** [comment]
`{
  'HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Internet Settings': {
    exists: true,
    keys: [
      '5.0',
      'Cache',
      'Connections',
      'Http Filters',
      'Lockdown_Zones',
      'P3P',
      'Passport',
      'Wpad',
      'ZoneMap',
      'Zones'
    ],
    values: {
      CertificateRevocation: [Object],
      DisableCachingOfSSLPages: [Object],
      IE5_UA_Backup_Flag: [Object],
      PrivacyAdvanced: [Object],
      SecureProtocols: [Object],
      'User Agent': [Object],
      ZonesSecurityUpgrade: [Object],
      WarnonZoneCrossing: [Object],
      EnableNegotiate: [Object],
      ProxyEnable: [Object],
      MigrateProxy: [Object],
      LockDatabase: [Object],
      'ProxyHttp1.1': [Object],
      EnableHttp1_1: [Object],
      _FiddlerDirectWrite: [Object]
    }
  }
}`

![image](https://user-images.githubusercontent.com/30630322/131747939-661ea783-8be4-4faf-9f77-f925dabd759f.png)

Using version 5.0.0

**Comment by kessler** [comment]
closing this issue, please reopen if needed
