### ISSUE TITLE
[Suggestion] Monitor a key for changes

### ISSUE THREAD

**Issue by danperks** [ironSource/node-regedit#92]
I've been looking for a way to monitor a key for changes and while I can do this manually by repeatedly checking the key, it would be nice if a solution was available in this library, as it would probably be more efficient than I am able to come up with!

**Comment by kessler** [comment]
did a little research about this.
StdRegProv does not support this directly but it can be achieved using other mechanisms: https://docs.microsoft.com/en-us/previous-versions/windows/desktop/regprov/stdregprov#remarks
however, I currently don't have the resources and time to invest in this. You are welcome to submit a PR
