### ISSUE TITLE
any way to send hex values instead of binary?

### ISSUE THREAD

**Issue by omiinaya** [ironSource/node-regedit#95]
I am attempting to recreate this script:
https://superuser.com/questions/949385/map-capslock-to-control-in-windows-10

My issue is that the vb script used by the put function will not take my hex numbers as a string.

I've been attempting to create an array that it will accept for hours... Any tips?

**Comment by kessler** [comment]
sorry for the later reply, if you want to provide a working code example, please reopen this issue
