### ISSUE TITLE
Version published on NPM is missing the type definitions

### ISSUE THREAD

**Issue by merwaaan** [ironSource/node-regedit#96]
Hi @kessler
(Sorry if this is not the right place for this kind of issue)

As the title describes, the version published on NPM is older that the October commit that added types.

Would it be possible to push a new version so that we can use them?
Thanks

**Comment by kessler** [comment]
yes, I'll take of this on the weekend!
my sincere apologies

**Comment by merwaaan** [comment]
Many thanks :)

**Comment by kessler** [comment]
@merwaaan will be delayed in a few days. As I'm updating the docs as well.
